# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfquiet" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "c9117f94a72e8d9ad434af5720fe1addfe3928df34c2ceef794304d2bcbc3fad"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "02a5d60ac735134b87cf3caeefc5dd91c671fe49804a330b8eb042d0ba853b59"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "463bb0455128044c8d5b563f3bccfccdb1b785abc535ec469a8a3a770a330ea7"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "671a18a0bc52e9039c07f712a1d63dbd78d8a5a421e64fcc4803fb1a9a7bc3e5"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfquiet"
  desc "tfquiet trims noise out of terraform plan output so the diff that matters stays in focus."
  homepage "https://github.com/winebarrel/tfquiet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfquiet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfquiet"]
    end
  end

  # No zap stanza required

end
