# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfquiet" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "d196e405fd76d5e7466e909763fc29fd387a4fb48b4294630f109311dbefb455"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a462299a529fbd1a7f8392d4b4dd10724f6f3676e69f2b9ed9ee894c87973707"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d6c5ad7659f1e957f233317c00db720c2e54fbfd8a4871e0624edb2bdc95697"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b82795d553324d36bf70e7953e3472b5f2c9d5a4723e73376b7f19c4baf56fc"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfquiet"
  desc "tfquiet trims noise out of terraform plan output so the diff that matters stays in focus."
  homepage "https://github.com/winebarrel/tfquiet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfquiet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfquiet"]
    end
  end

  # No zap stanza required

end
