# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfquiet" do
  version "1.3.2"

  on_macos do
    on_intel do
      sha256 "fcc38e1a381a19e1fe98282521b1f8758e3827b36728e239aa538c74fa43aa3c"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "09ed464998ff61bf52dc2937e890c68c91721f896b04e79edbd8f37dc6a4f7a6"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "733b80e7a64c7449eec492a0b1a2214539ca3d252949c72e88acdf891e4dbc53"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d813bcb40626d646118f3cbac497e6f40b2c317d918eff74a09403a85bb434fc"
      url "https://github.com/winebarrel/tfquiet/releases/download/v#{version}/tfquiet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfquiet"
  desc "tfquiet trims noise out of terraform plan output so the diff that matters stays in focus."
  homepage "https://github.com/winebarrel/tfquiet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfquiet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfquiet"]
    end
  end

  # No zap stanza required

end
